### PR TITLE
Ft admin see orders 160087939

### PR DESCRIPTION
**Pull request by Darius-Ndubi**
#### What does this PR do?
  Shows the admin endpoint

#### Description of Task to be completed?
- Allow the admin to see all orders
- Admin able to accept or decline an order
- Admin able to mark orders as complete or not
- Links for the admin to add, edit, delete fast food items

#### How should this be manually tested?
- Fork the [repo](https://github.com/Darius-Ndubi/Fast-Food-Fast)
- git clone https://github.com/Darius-Ndubi/Fast-Food-Fast.git
- cd Fast-Food-Fast
- git checkout ft-admin-see-orders-160087939
- open admin_profile.html in a browser
- https://darius-ndubi.github.io/admin_profile.html

#### What are the relevant pivotal tracker stories?
[#160087939](https://www.pivotaltracker.com/story/show/160087939)
[#160087863](https://www.pivotaltracker.com/story/show/160087863)
[#160087855](https://www.pivotaltracker.com/story/show/160087855)

### CODE REVIEW

**Comment by artorious** [comment]
Looks great. 
As you proceed building consider having summary line in ur commit messages then more details like you've done. 

Eg.
[Feature #160087241] summary message

Commit msg in detail
Commit msg in detail also

**Comment by Darius-Ndubi** [comment]
Okay will do that.

**Comment by iddle254** [comment]
nice UI

**Comment by dmithamo** [comment]
In the section on _Manual Testing_ , I think it is sufficient to simply provide a link to your GitPages hosted page. That also applies for the screenshots.
Providing a link, instead of screenshots and instructions for cloning the repo, minimizes on the amount of write up you do in the PR.

**Comment by Darius-Ndubi** [comment]
thanks @dmithamo and @iddle254   let me remove redundant information

**Pull request merged**
